apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tIjp7InVzZXJuYW1lIjoiY3Nua2FydGhpayIsInBhc3N3b3JkIjoiU3dldGhhUkB0aGkyMDA5IiwiZW1haWwiOiJrYXJ0aGlrLmFzcHguY3NAZ21haWwuY29tIiwiYXV0aCI6IlkzTnVhMkZ5ZEdocGF6cFRkMlYwYUdGU1FIUm9hVEl3TURrPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: helm-secret
type: kubernetes.io/dockerconfigjson
